version: '3.5'
services:
  starter_mongo:
    image: mongo
    container_name: starter_mongo
    restart: unless-stopped
    volumes:
      - mongo_data:/data/configdb
      - mongo_data:/data/mysql
    ports:
      - 27017:27017
    networks:
      - starter_network
volumes:
  mongo_data:
    name: global_mongo